# Schema search path. The server defaults to $user,public
#schema_search_path: myapp,sharedapp,public

# Minimum log levels, in increasing order:
#   debug5, debug4, debug3, debug2, debug1,
#   log, notice, warning, error, fatal, and panic
# The server defaults to notice.
#min_messages: warning

common: &common
  host: localhost
  adapter: postgresql
  username: postgres
  password: postgres

development:
  <<: *common
  database: cidadao_alerta_development

test:
  <<: *common
  database: cidadao_alerta_test
  min_messages: WARNING

production:
  <<: *common
  database: cidadao_alerta_production
